- name: Test sudo
  hosts: all
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: Qui suis-je ?
      command: whoami
      register: result_root
      become: yes

    - name: Afficher le résultat
      debug:
        var: result_root.stdout
